apiVersion: v1
kind: Service
metadata:
  name: SERVICE
  namespace: NAMESPACE
  labels:
    project: akri
    component: webhook
    language: rust
spec:
  selector:
    project: akri
    component: webhook
    language: rust
  ports:
    - name: http
      port: 443
      targetPort: 8443
